version: '3.7'
services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: landing-db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: dev-password
      MYSQL_USER: landing-user
    networks:
      landing:
        ipv4_address: 11.0.1.253


networks:
  landing:
    ipam:
      config:
        - subnet: 11.0.1.0/24
